# Generated by Django 5.2.13 on 2026-04-29 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_source_cancel_queue_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('processing', 'Wird verarbeitet'), ('done', 'Fertig'), ('failed', 'Fehlgeschlagen'), ('cancelled', 'Abgebrochen')], default='processing', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lm_studio_model', models.CharField(blank=True, max_length=255)),
                ('prompt_version', models.CharField(blank=True, max_length=40)),
                ('raw_lm_studio_response', models.TextField(blank=True)),
                ('error_details', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='extractionattempt',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extraction_attempts', to='recipes.recipesource'),
        ),
        migrations.AddIndex(
            model_name='extractionattempt',
            index=models.Index(fields=['source', '-started_at'], name='recipes_ext_source__c2c94b_idx'),
        ),
        migrations.AddIndex(
            model_name='extractionattempt',
            index=models.Index(fields=['status'], name='recipes_ext_status_e239d8_idx'),
        ),
    ]
