# Generated by Django 5.2.13 on 2026-04-29 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_extractionattempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lm_studio_base_url', models.URLField(blank=True)),
                ('lm_studio_model', models.CharField(blank=True, max_length=255)),
                ('transcript_limit', models.PositiveIntegerField(default=30000)),
                ('language_preference', models.CharField(blank=True, max_length=40)),
                ('extraction_prompt', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App settings',
                'verbose_name_plural': 'App settings',
            },
        ),
    ]
