# Generated by Django 5.2.13 on 2026-04-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_tag_recipe_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipesource',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('text', 'Text')], default='youtube', max_length=20),
        ),
    ]
