# Generated by Django 5.2.13 on 2026-04-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_recipesource_source_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipesource',
            name='source_type',
            field=models.CharField(choices=[('youtube', 'YouTube'), ('website', 'Webseite'), ('text', 'Text')], default='youtube', max_length=20),
        ),
    ]
